import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Banner from '../components/Banner'
import Footer from '../components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Biologging Sensor',
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* ALA dependencies */}
        <base href="/" />
        <link rel="stylesheet" type="text/css" href="https://static.biodiversitydata.se/css/bootstrap.min.css" />
        <link rel="stylesheet" type="text/css" href="https://static.biodiversitydata.se/css/bootstrap-theme.min.css" />
        <link rel="stylesheet" type="text/css" href="https://static.biodiversitydata.se/css/ala-styles.min.css" />
        <link rel="stylesheet" type="text/css" href="https://static.biodiversitydata.se/css/font-awesome.min.css" />

        {/* SBDI dependencies */}
        <link rel="apple-touch-icon" sizes="180x180" href="https://static.biodiversitydata.se/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="https://static.biodiversitydata.se/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="https://static.biodiversitydata.se/favicon-16x16.png" />
        <link rel="manifest" href="https://static.biodiversitydata.se/site.webmanifest" />

        {/* CSS generated by brunch */}
        <link rel="stylesheet" href="https://static.biodiversitydata.se/css/app.css?DIGEST" />

        {/* Leaflet map */}
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
          integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
          crossOrigin="" />
      </head>
      <body className={inter.className}>
        <Banner />
        {children}
        <Footer />
        <script async src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
          integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
          crossOrigin=""></script>
      </body>
    </html>
  )
}
